version: '3'

# Containers
services:
  # NGINX
  nginx:
    build:
      context: ./build/nginx
    container_name: saber_nginx
    depends_on:
      - php
    image: lemp-stack/nginx
    networks:
      lemp-stack:
    ports:
      - ${APP_PORT:-80}:80
      - ${APP_SSL_PORT:-443}:443
    restart: always
    volumes:
      - ./code:/var/www/code
      - ./lemp/nginx/config:/etc/nginx
      - ./certs:/etc/ssl/custom
      - phpsocket:/var/run/socket
    working_dir: /etc/nginx
  # PHP-FPM
  php:
    build:
      context: ./build/php
      args:
        version: ${PHP_VERSION}
    container_name: saber_php
    depends_on:
      - db
    image: lemp-stack/php-fpm
    networks:
      lemp-stack:
    ports:
      - ${PHP_PORT:-9000}:9000
    restart: always
    volumes:
      - ./code:/var/www/code
      - ./lemp/php/php.ini:/usr/local/etc/php/php.ini
      - ./lemp/php/config:/usr/local/etc/php-fpm.d
      - phpsocket:/var/run/socket
    working_dir: /var/www/code
  # MariaDB
  db:
    build:
      context: ./build/db
      args:
        db_name: ${DATABASE_NAME}
    container_name: saber_db
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DATABASE:-default}
    image: lemp-stack/db
    networks:
      lemp-stack:
    ports:
      - ${DB_PORT:-3306}:3306
    restart: always
    volumes:
      - db_data:/var/lib/mysql
# Networks
networks:
  lemp-stack:
# Volumes
volumes:
  db_data:
  phpsocket:
